### ISSUE TITLE
Can chunkc query window details X return PID?

### ISSUE THREAD

**Issue by Nicktho** [koekeishiya/chunkwm#102]
I'm trying to write a khd binding so that it only sends ctrl + h,j,k or l if the current running process of the current focused window is vim.

I got as far as `id=$(chunkc query _focused_window); chunkc query window details $id` though no PID is returned.

Having a brief look in the source (fyi: I don't know C) I can see the PID stored against a window type, so is it possible to expose that in the query?

If not, would you happen to know a way of getting the process id from a window id?

**Comment by koekeishiya** [comment]
The information is cached internally yes.

The *_focused_window* variable has been removed in the latest release due to limits in macOS causing our cached focus to become out of sync quite often.

 The reason this got out of sync is that some actions in the system that happened quite frequently does not report back to us through the observation API that macOS provides, and so we no longer try to cache this info anymore.

You can comment in #38 regarding information that you think could be useful to have exposed, and we can discuss implications and behaviour further. 

Closing this as duplicate.
