### ISSUE TITLE
Is it possible to get the name of the current focused window from the command line?

### ISSUE THREAD

**Issue by ohwillie** [koekeishiya/chunkwm#110]
Hey there, I'm trying to use https://github.com/herrbischoff/nerdbar.widget with chunkwm. nerdbar.widget uses `kwmc` to get the name of the currently focused window. Is there a way to do that with `chunkc` at the current moment that I'm not seeing? I'm able to get the ID of the currently focused window with `chunkc get _focused_window`, but not the name. Thanks!

**Comment by koekeishiya** [comment]
_focused_window was removed in a recent commit due to sync issues. see #102 for reason why.

There is currently no option to get information such as the focused window, but this is something that can be implemented. There are different ways to do this. Please post any requests in #38 

Closing this as duplicate.

**Comment by ohwillie** [comment]
thanks!
