### ISSUE TITLE
[plugin|tiling/ffm] focused_window_float with multiple windows

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#112]
I have a rule that keeps specific windows of an application floating, while the main window is tiled. When I close one of those windows and the tiling window is focused, ffm doesn't work until I focus another app/change space. `focused_window_float` isn't getting cleared I suppose?

**Comment by choco** [comment]
If I have 3 windows, one tiling and two floating i can:
1- focus a floating one
2- focus the other floating one (this is so when closing this window the one focused before, a floating one, will be focused)
3- close window
4- remaining floating window is focused, but standby_on_float isn't set

**Comment by koekeishiya** [comment]
That is a problem that we cannot fix without caching of the focused window, but we cannot properly cache the focused window because macOS does not report focus_changed notifications after e.g: browser ui elements (url tooltip) etc is destroyed, leaving our cached window out of sync.

The only way to fix that would be to call request focused application -> request focused window -> translate windowref to cgwindowid -> update cache upon every window_destroyed event.

**Comment by koekeishiya** [comment]
> The only way to fix that would be to call request focused application -> request focused window -> translate windowref to cgwindowid -> update cache upon every window_destroyed event.

Correction, we would only have to do the above when the window passed with the window_destroyed event is flagged as an invalid window. Will take a look at doing this approach.
