### ISSUE TITLE
Cursor position resets to center when clicking on menu bar items

### ISSUE THREAD

**Issue by keithyang** [koekeishiya/chunkwm#148]
When both focus-follow-mouse and mouse-follow-focus are enabled, as well as the menu bar set to automatically hiding, when clicking on menu bar items, the cursor position will be reset to the center of the current window in focus. 

Is there a way to keep the cursor on the menubar after an item is clicked on?

**Comment by crisidev** [comment]
I have the same issue.

**Comment by koekeishiya** [comment]
I don't really have an issue using the menubar, same settings as mentioned above?? Steps to reproduce please.

**Comment by keithyang** [comment]
@koekeishiya Thanks for the reply. This issue only happens when you choose to automatically hide and show the menu bar in system preferences; when the menu bar is fixed to the top of the screen, clicking on an item does not cause the cursor to be reset to the center of the current window in focus. Please let me know if you need further information.

**Comment by koekeishiya** [comment]
I'm running with hidden menubar as well, and unable to reproduce.
Any particular applications this happen for?

**Comment by keithyang** [comment]
Do you also have mouse-follow-focus turned on? This happens no matter which application I'm using.

**Comment by crisidev** [comment]
It happens on all applications to me.. I have also the Dock hidden and I am using chwm-sa.

My chunkwm configuration: https://pastebin.com/gqz2cp46

**Comment by koekeishiya** [comment]
Just tried again with ffm, mff, chwm-sa, dock hidden, menubar hidden, works just fine.
Can you upload a gif?

**Comment by keithyang** [comment]
![issue 148](https://user-images.githubusercontent.com/4432911/28250370-8296dba6-6a34-11e7-8f19-024152478faf.gif)

**Comment by koekeishiya** [comment]
So the problem is that (I assume you are both using *Übersicht* and that is what I'm seeing at the top in your gif. What happens is that you mouse-over the *Übersicht* bar, and it steals application focus. When your cursor then hits the macOS menu-bar, it activates the application again, triggering an *application_activated* event, causing a *mouse-follows-focus* to happen, moving the cursor back to the focused window for the application.

This is not really an issue with the logic in *chunkwm*, but with how *Übersicht* works.
If I start *Übersicht*, I'm able to reproduce. In fact, I receive the "<focused app> deactivated" event when I'm like 1/4th of my screen height AWAY from the the *20 px Übersicht bar*.

**Comment by crisidev** [comment]
Yes, I am using Übersicht.. It is not a real issue for me since if you keep the mouse "clicked", you can move to the menu. Do you think there can be a workaround with chunkwm or should we open an issue to Übersicht ?

**Comment by keithyang** [comment]
I was not able to reproduce it with Übersicht turned off. Does that mean there will not be a way for chunkwm and Übersicht menu bar to coexist while at the same time preventing Übersicht from stealing focus?

**Comment by koekeishiya** [comment]
> Do you think there can be a workaround with chunkwm or should we open an issue to Übersicht ?

The ffm plugin I wrote for chunkwm uses a private API: `CGSFindWindowByGeometry()` which does all z-ordering, specific collision-regions for windows (so context menus etc all work properly now), and is way more performant than the custom solution I had before.

The sideeffect is that I cannot simply skip the "top window" or something like that, as I did in *kwm*.
This is something that is very likely to have to be fixed in *Übersicht*. No idea how that application is implemented and if a potential fix is hard / possible without breaking functionality.

**Comment by keithyang** [comment]
Thanks! I guess we could close this issue now.

**Comment by koekeishiya** [comment]
On latest master, you can define `chunkc set mouse_modifier <list of mods separated by whitespace>`

holding these modifiers down will temporarily prevent ffm from triggering.
These are the same modifiers used for mouse-interaction for bsp-swap and bsp-resize.

This is as close to a fix as I can provide from *chunkwm*'s side, I think.

**Comment by keithyang** [comment]
Thank you so much!

**Comment by crisidev** [comment]
Thanks a lot!

**Comment by crisidev** [comment]
Oddly if I have the modifier set up and I try to click on the menu, it just does not click :(

Configuration:
```
######################
# mouse modifier
######################
chunkc set mouse_modifier                fn
chunkc set preselect_border_color        0xff59ad6b
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       8
```

**Comment by koekeishiya** [comment]
You'll have to release the modifier after you have moved the mouse to the menu-bar.

The same modifier is also used for *chunkwm-tiling* mouse-interactions which suppresses the left/right click.

**Comment by crisidev** [comment]
Ahhh, thanks! It works perfectly.
