### ISSUE TITLE
[plugin|tiling] Deal with open in background

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#160]
Many apps provide a way to open links in the background (mail client, twitter client etc...)
When I click on these a window focused event is triggered, but the current app isn't deactivated.
chunkwm seems to handle this well, but the cursor will still move to the center of the new window opened by that link, even if it on a different space.

**Comment by koekeishiya** [comment]
Not sure what can be done about this.
The only place we call *center cursor* is in the [*WindowFocusedHandler*](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/plugin.mm#L1185)

We cannot filter by "is this window on our active space" because this breaks normal focusing across spaces and monitors.

The reason chunkwm can handle it just fine, with the exception of the cursor, is that we do not use the window_id that we cache in our *focused window handler* for anything except *ffm standy-on-float* for exactly this reason.

If you are able to come up with a solution that would be great, but as far as I'm concerned this is unfixable.

**Comment by koekeishiya** [comment]
Potential fix, with undetermined level of sideeffects:
```
# add the following requirement for window received in WindowFocusedHandler
CFStringRef Display = AXLibGetDisplayIdentifierFromWindow(Window->Id);
macos_space *Space = AXLibActiveSpace(Display);
AXLibSpaceHasWindow(Space);

# query macOS focused window of space at the end of SpaceAndDisplayChangedHandler
macos_window *Window = GetFocusedWindow();
if(Window)
{
    WindowFocusedHandler(Window);
}
```

**Comment by koekeishiya** [comment]
Fixed with minor sideeffect, see TODO in commit.
