### ISSUE TITLE
Spaces naming, management

### ISSUE THREAD

**Issue by areteCocoa** [koekeishiya/chunkwm#170]
Using KWM I utilized space naming (https://koekeishiya.github.io/kwm/kwmc.html#space-defaults) in an Ubersicht widget that allowed me to see which space I was in based on name. However, I can not find any way to name a space within chunkwm at the moment.

Will this be a new plugin and/or is it possible to develop a plugin to do this? I am interested in attempting it but am unsure if it is within the capabilities of chunkwm.

**Comment by koekeishiya** [comment]
*chunkwm* only relies on the *mission-control* index, where as *kwm* used the internal macOS space identifiers.

Because of this, I think it is better to leave the space name mapping to the widget itself.
Basically, query *chunkwm* for the *focused desktop* index, then just have a string table in your widget that returns the name you want for that desktop, using the index.

**Comment by areteCocoa** [comment]
Should plugins be developed as separate repositories to chunkwm or as a fork and then pull request?

**Comment by koekeishiya** [comment]
separately wouldd be preferred.

**Comment by areteCocoa** [comment]
Does this mean a chunkwm package manager may be beneficial should an expansive library of plugins emerge?

**Comment by koekeishiya** [comment]
That was the initial idea, yes. I do not want to bother with these things until we reach a point where people are actually interesting in using the *chunkwm-core* for their own ideas though.

See some of the posts here: https://github.com/koekeishiya/chunkwm/issues/67
Some of the posts don't apply, so may have to filter.
