### ISSUE TITLE
Previous/next window order

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/chunkwm#172]
When I have a 2x2 window layout, navigating to previous/next works in this order, top to bottom, left to right -

```
[ 1 ] [ 3 ]
[ 2 ] [ 4 ]
```

However, I'd prefer this, starting from top left, navigating in a circular motion -

```
[ 1 ] [ 4 ]
[ 2 ] [ 3 ]
```

Is this possible with chunkwm?

**Comment by koekeishiya** [comment]
The prev / next simply navigates to the next leaf node in the binary tree.

In your first example, the tree looks like this:
```
        a 
      /   \
    b      c
  /  \     /  \
 1   2  3   4

a: vertical split
b: horizontal split
c: horizontal split
```

Personally, I use directional focusing when I have more than 2 windows on a single desktop.

You can certainly navigate the tree in different ways, but it requires you to edit the source code and implement whichever system you want. This is not something I'll be looking to do, as it seems ambiguous for more complex binary trees.

**Comment by carymrobbins** [comment]
I believe chunkwm's major improvement over kwm is its ability to leverage plugins; is this something a plugin may be able to do, one that provides different tiling layouts? If so, seems better than forking.

**Comment by koekeishiya** [comment]
>  is this something a plugin may be able to do, one that provides different tiling layouts? If so, seems better than forking.

You can create your own tiling plugin that revolves around layouts rather than binary-trees as I have chosen. You still have to do a great deal of work, as you would then create the window manager from scratch.

What the plugin architecture does is provide an abstraction of the macOS system APIs, and provide events directly for the plugin to receive and respond to (e.g: window created, application launched and so on).

**Comment by carymrobbins** [comment]
Ok then, sounds like more work than it's worth given I can probably live with the prev/next order in exchange for more time. Thanks @koekeishiya!
