### ISSUE TITLE
[plugin|tiling] Add tiling::rule --state native-fullscreen

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#180]
Feature request: add a tiling rule for `native-fullscreen`ing a window on spawn. This might be useful for video players, iBooks.app (see #167) or other applications that do just not resize well.

Syntax suggestion:

```
chunkc tiling::rule --owner iBooks --state native-fullscreen
```

**Comment by dominiklohmann** [comment]
@koekeishiya This fails if the rule gets applied to two windows in the same space. chunkwm tries to set native-fullscreen for the second window while the first one is transitioning.

**Comment by koekeishiya** [comment]
At a higher perspective, we would want to queue these as some form of *events* and process them one by one, however, I don't see a way to be able to properly determine that some event has finished executing (as in the case of OS animations) which make the state very hard to track.

I would suspect that this incident almost always happen during the actual startup of *chunkwm*.
Because of the above, I'm tempted to say that this is just a limitation of the system, unless we can somehow flag a window fullscreen and not trigger the transition to the newly created space. I severely doubt this is possible though.
