### ISSUE TITLE
Plugin development

### ISSUE THREAD

**Issue by lego** [koekeishiya/chunkwm#196]
While the existing PDF is excellent for understanding how to build a plugin I think there is still a lot that can be done for documenting the process of building a plugin to help others experiment.

A few specific questions I have,
- How do you go about debugging a plugin? i.e. use GDB
- What makes a plugin use the Obj-C runtime, i.e. prevent hot-loading
- Do other people have plugins they've built that you know of? It would be great to have a list of them somewhere -- either an issue or a markdown file :)

(love the plugin PDF and the work you all have done <3)

**Comment by koekeishiya** [comment]
> While the existing PDF is excellent for understanding how to build a plugin I think there is still a lot that can be done for documenting the process of building a plugin to help others experiment.

The plugin PDF is actually outdated (ABI v3, current ABI is v5). There has been minor changes to data passed from *chunkwm* to the plugin, but the structural information and getting started process should still be correct. The template plugin is updated, so using that as a start will work.

> How do you go about debugging a plugin? i.e. use GDB

I personally think GDB is terrible. Most of my serious projects uses a unity-build setup, so I find it faster to just do printf debugging when I'm doing development on macOS, as compile times are nearly instantaneous.

> What makes a plugin use the Obj-C runtime, i.e. prevent hot-loading

Don't have any specifics here, but using any native obj-c classes, methods, datatypes and what not.
I try to avoid obj-c as much as possible, but that is a hard trick these days when writing software for mac. Specific to *chunkwm*, using window borders or monitor functionality in a plugin will pull in the obj-c runtime.

> Do other people have plugins they've built that you know of? It would be great to have a list of them somewhere -- either an issue or a markdown file :)

I do not know of anyone really that has taken any interest in the plugin system, which is why it is quite immature and undeveloped. Because of this, I have not bothered spending time to further iterate on the system beyond my own personal needs.

**Comment by piotryordanov** [comment]
```
The template plugin is updated [...]
```

How exactly can this plugin be used? And, what is it for? Can it be used to create default layouts?

**Comment by koekeishiya** [comment]
Just to expand a bit on this.

1. If you actually want to debug plugins, you can do this by launching chunkwm in e.g *gdb*. Put a breakpoint after *dlload(..)* is called. When *gdb* hits this breakpoint, it will have loaded the symbols from the shared library that was just loaded into memory, and you can then place breakpoints for these symbols.

3. There is one plugin I'm aware of https://github.com/splintah/blur The same person is also working on a plugin API-bridge for Rust.

I'll be closing this issue for now. Some of this information will probably be added to the *plugin api docs* the next time they are updated.
