### ISSUE TITLE
Alternative to workspaces

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/chunkwm#200]
In XMonad, workspaces are global and can be easily swapped between monitors. On OSX, each monitor has its own workspaces.

Is it currently possible to simulate how XMonad works by having something like a global workspace which can be moved and hidden across monitors? If this exists in someway, even if it requires some sort of complicated configuration, I'd be ok with it if you could provide some sort of an example of how to pull this off.

**Comment by koekeishiya** [comment]
There does not exist a way to do this that I know of.

However, we could build our own virtual workspace system that works the way we want. We then have to map that workspace to a given monitor. We can use the low-level CGSSpaces API to create, destroy, and set the active space. The drawback so far has been that these API's do not update mission-control,
but we could use them in our own system.

Granted this would function more like a *scratchpad* kind of thing, except that instead of designated windows, you'd be able to pull up an entire space instead, on whichever monitor you want.

Some quick thoughts:

We would need some way to specify the size of the workspace so that we can calculate the proper regions when we *view* this workspace. Monitors can run at different resolutions, so we'd likely define the workspace properties *x_pos, y_pos, width, height* as percentages of the monitor we are displayed on.

quick (incomplete) sample of what this might look like:
```
struct workspace {
    int monitor_id; // monitor we are being displayed on; -1 = not currently viewed
    float x_pos, y_pos, width, height; // 0 -> 1 where 1 = 100% or displayed monitors property
    node *Tree;  // window representation
    ..
};

// view workspace *ws* on monitor *monitor_id*
void workspace_view(struct workspace *ws, int monitor_id);
void workspace_hide(struct workspace *ws);
```

If this sounds interesting, let me know and I can spend some time actually thinking about how such a system might work. Suggestions or comments regarding how something like this should work from the user pov would be great.

**Comment by Alok** [comment]
I'd like this to be implemented.

**Comment by koekeishiya** [comment]
Uh, so after thinking some about this, the *CGSSpaces* APIs would still cause issues for native-fullscreen etc, and so this is not really a realistic goal.

Closing.
