### ISSUE TITLE
[plugin|tiling] Allow changing window focus in splitscreen native-fullscreen desktops

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#224]
When using macOS native-fullscreen it is possible to use two windows side-by-side. Changing focus with mouse-follows-focus works here, but all focus commands (relevant: prev, next, east, west) are disabled. 

Suggestion: If a native fullscreen window contains more than one (two to be specific) tileable windows, allow changing the window focus with prev, next, east, west focus commands.

To activate splitscreen native-fullscreen, either force touch (or click and hold) the maximize button on a window and select the second window or drag a window on a native-fullscreen desktop in mission control. This has been a feature since macOS 10.12 Sierra if I recall correctly.

**Comment by koekeishiya** [comment]
Considering that there are maximum two windows in a native-fullscreen desktop, would a simplified implementation that simply just alternates focus be good enough? If so, I already have a working implementation of this.

Basically, `chunkc tiling::window --focus `north | east | south | west | prev | next` would all just alternate focus between the two windows, with no notion of direction. Because of this, there is no notion of "focus-cycle" either.

The main reason for this is that the current code that focuses based on directions relies on the node regio, and not the window dimensions themselves. This is because of issue where windows that has minimum and maximumsizes would not receive proper priority in the focus-logic. 

It is possible to make it behave the same way as the other focus commands if that is desired, but need some time to think about how to restructure the old code.

Out of curiosity, have you also tested if resizing one of the windows through the AX API is possible, and in that case, does it automatically adjust the split between these windows?

**Comment by koekeishiya** [comment]
Having the focus alternate regardless of the command felt wrong. I went with the other approach. Need to perform some cleanup before pushing the changes.

**Comment by koekeishiya** [comment]
So scratch the previous post.

`chunkc tiling::window --focus ..` works exactly the same way in split native-fullscreen desktops as it does in normal bsp desktops. It does respec the `cycle-focus` setting, but it cannot cycle between monitors.

**Comment by dominiklohmann** [comment]
> there are maximum two windows in a native-fullscreen desktop

This is a false assumption - some applications like Mail can spawn additional windows on top and it is also possible to move windows to a fullscreen space (without making them fullscreen) using the AX API.

> Out of curiosity, have you also tested if resizing one of the windows through the AX API is possible, and in that case, does it automatically adjust the split between these windows?

Not possible. Seems to be some new API sadly.
