### ISSUE TITLE
[plugin|tiling] Crash with ApplyWindowRule & SendWindowToDesktop

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#236]
I've been experiencing this crash for quite some time, the crash is here https://github.com/koekeishiya/chunkwm/blob/1f80646a13789577adbb5435307f7104448ddcc9/src/plugins/tiling/controller.cpp#L1637
The spaces list is null and we try to dereference it.
This happens when:
1. i have a rule set up to move a window to a desktop
2. a window matching the rule is created
3. ApplyRule tries to SendWindowToDesktop
4. CGSCopySpacesForWindow doesn't return any space for the window
5. AXLibWindowSpaces returns empty list
6. SendWindowToDesktop crashes

EDIT: The non-reliabity of that private functions probably bites us in other places :(

**Comment by choco** [comment]
Right now as a stopgap solution I'm just retrying a bunch of times if `CGSCopySpacesForWindow` returns `0` spaces, with some waiting in between, and it works decently.

**Comment by koekeishiya** [comment]
> The non-reliabity of that private functions probably bites us in other places :(

I think the reason this is an issue is because we try to move the window as soon as it is created, thus the internal information has yet to propogate to whatever state the *CGSSpaces* API queries.

We do not really need to know the desktop that the window is currently on, as there is a private API where we just specify the CGSWindowID and destination CGSSpaceID, and it performs the move.
This will break support for specifying "next" and "prev" desktop though.

**Comment by koekeishiya** [comment]
Should be fixed at master. See commit message and notes in the commit for details.
