### ISSUE TITLE
Remove window decorations

### ISSUE THREAD

**Issue by xiamaz** [koekeishiya/chunkwm#253]
Coming from linux I wonder whether it would be possible to remove the window titlebars for tiled windows, similar to the behavior of other tiling window managers. Sorry if this feature is already implemented and I missed it in the documentation.

**Comment by dominiklohmann** [comment]
See discussion in koekeishiya/chwm-sa#4 (specifically the part about [winBuddy](https://github.com/w0lfschild/winBuddy)).

chwm-sa is a scripting addition that can be used to alter system behaviour by injecting code into Dock.app. It is unlikely to ever be built into chunkwm since the installation of the scripting addition is not trivial. chunkwm has some optional plugins like purify that rely on chwm-sa.

**Comment by koekeishiya** [comment]
Closing this as can't be done. While it is technically possible, it requires injecting code into the specific application, iterating through its windows and setting their stylemasks, as mentioned in https://github.com/koekeishiya/chwm-sa/issues/14
