### ISSUE TITLE
Get Window by ID failed

### ISSUE THREAD

**Issue by NTT123** [koekeishiya/chunkwm#267]
My stack trace

![Imgur](https://i.imgur.com/DCi9WIc.png)

I guess I got this problem when one of my application crashed suddenly. It could be the reason why `get window by ID` failed.

**Comment by koekeishiya** [comment]
This seems related to #266 ?

**Comment by NTT123** [comment]
Yes, I've thought the same thing.

**Comment by koekeishiya** [comment]
So this is actually not related to #266. Will look at this at some point.

**Comment by koekeishiya** [comment]
I've replaced the assert with a guard -> return for now, so we do nothing instead of causing a crash.
Still have not found a way to reproduce this reliably, so not sure if a guard is the correct fix or not.

Closing this issue as its related information to the assert rather than how it was triggered.
