### ISSUE TITLE
Focus another window on the same desktop when focused window closes

### ISSUE THREAD

**Issue by dplisek** [koekeishiya/chunkwm#281]
The default macOS behavior when one closes a window of an application is that the same application stays "focused" (i.e. the menu still belongs to the application whose window was closed). chunkwm respects this behavior, but from a tiling window manager user's point of view this is very clunky. 

Example:

1) Have two windows open on a desktop belonging to two different applications, e.g. Chrome and iTerm. Tiled. 

2) Give focus to the iTerm window.

3) Close the iTerm window (either by pressing CTRL+D to log out of the iTerm session, or by clicking the red close button, or by pressing CMD+W, or using one's shortcut for the chunkc window close operation.

4) There is now only one Chrome window spanning the entire screen, but it's not focused. The top menu still belongs to iTerm, which has no windows on the screen.

5) One cannot even use a chunkc focus command to select the Chrome window, so one has to either click it (mouse???) or press CMD+TAB to switch to the Chrome application.

Proposed solution:

When a window closes, automatically focus its sibling, if one exists.

**Comment by dplisek** [comment]
I considered biding a select sibling command to the window close operation, to at least make this work when I close the window deliberately using the chunkc close window command. I don't know how to do this in chunkc, though. If anyone has an idea, please share. Much obliged.

**Comment by koekeishiya** [comment]
macOS has some very tailored behaviour with regads to focus, and so I have opted not to interfere at all with how macOS does its things, in chunkwm. I did try to "make it better" in *kwm* by overriding focus behaviour after window closed, and so on, and it just didn't feel good due to consistency problems.

With that said, I do agree that it is not optimal behaviour and it would be great if we could come up with a solid solution that would feel natural to use.

Personally, I think having a fuzzy-searchable window switcher would be the best addition to improve upon said focusing-issues. I realize that is overkill and also more time consuming for such a simple operation as you request.

There is currently no method that chunkwm exposes to the user to achieve this, but it is not "hard" to add support for this in the codebase, although with the caveats that I did mention earlier.

One issue that comes to mind is that when an application is closed, we will sometimes receive a window closed event followed by an application terminated event, and in other cases we only get the application terminated event. This can cause an inconsistency to happen causing the refocus to sometimes fail.

Roughly, this is how it looks like now:

 - window closes
 - macOS focus other window of application if available, or the application itself

We have to inject a 3rd event, basically like so:

 - if the window that closed was our currently focused window, focus sibling

**Comment by dplisek** [comment]
Hi, thanks for the quick and elaborate answer.

I have another suggestion. Consider a situation where no window is focused. Could all the 
`chunkc tiling::window --focus *`
commands select e.g. the first leaf node or something like that? To prevent the situation which arises now, where there is no window focused and none of the window focus key combinations work.

Specifically, consider the situation I described in point 4 of the initial report. Pressing my key combination which switches focus to another window would select the single Chrome window. Additionally, I could map my close window key combination to execute
`chunkc tiling::window --close; chunkc tiling::window --focus next`
which would not always go to the sibling, but would at least get me back into my window focus management.

**Comment by koekeishiya** [comment]
That's a pretty good solution. If I'm not mistaken, there is actually a *TODO* in the codebase for the focus commands to do exactly that. Will try and look into it some time during the weekend.

**Comment by dominiklohmann** [comment]
If you do that, can you make next, east and south focus the first node and prev, west and north focus the last node?

**Comment by dplisek** [comment]
Well according to the documentation, there's also a `biggest` option to go with `--focus`. I would find it meaningful to use that to get back into the game from having no window selected. 

However, the option didn't seem to work even in a regular scenario. Do I understand it correctly that it should selected the leaf node which is the highest one up the tree?

**Comment by koekeishiya** [comment]
> However, the option didn't seem to work even in a regular scenario. 

That option is implemented on master, but not in the latest brew release.
It will focus the leaf node with the highest area.

**Comment by koekeishiya** [comment]
suggested change has been implemented on master.

**Comment by dplisek** [comment]
Thanks a bunch!

**Comment by dplisek** [comment]
Confirmed working.

For anyone wishing to automize this, there seems to have to be a slight delay between closing a window and focusing another one, otherwise it doesn't work reliably. This seems to be fine after brief testing:

# close focused window
ctrl - w : chunkc tiling::window --close;\
           sleep 0.1;\
           chunkc tiling::window --focus next
