### ISSUE TITLE
Region resize key binding example

### ISSUE THREAD

**Issue by dplisek** [koekeishiya/chunkwm#282]
I recommend adding an example for a more user friendly region resize hotkey setup. This is the behavior as I know if from e.g. the i3 window manager. If you don't consider this the proper behavior, you can close this issue immediately and I won't say a word.

`# change region size
shift + alt - a :  chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge west; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge east

shift + alt - s :  chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge south; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge north

shift + alt - w   :  chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge north; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge south

shift + alt - d : chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge east; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge west`

Only one of the two chained commands gets executed in each of the four scenarios. The setup can be described as moving the region separators in the specified direction instead of making the regions explicitly larger/smaller.

**Comment by koekeishiya** [comment]
It's not so much what I consider proper behaviour or not, the sample config is just my own personal configuration as is. I don't really want to have to deal with "best practices", but if someone wants to do this I am more than happy to accept a PR.

Otherwise, I have opened the wiki for everyone to edit. such that configurations that are similar to what people use in somewhat related X Window Managers and whatever the community find useful can be posted there.

**Comment by koekeishiya** [comment]
I've been trying this out a little bit and it does have issues where you are not freely able to control the sizing properly when you are in certain type of nested tree.

I'll add an entry to the wiki page regarding this though.

**Comment by koekeishiya** [comment]
Link to wiki entry: https://github.com/koekeishiya/chunkwm/wiki/Useful-tips-and-workarounds
