### ISSUE TITLE
Rule-based windows aren't floated on startup

### ISSUE THREAD

**Issue by arxanas** [koekeishiya/chunkwm#294]
I usually have a little TextEdit window open with some notes. I have this rule to float TextEdit windows:

```
chunkc tiling::rule --owner TextEdit --state float
```

Expected behavior:

1) Open a TextEdit window.
2) Launch `chunkwm`.
3) TextEdit window stays where is it because it's marked as floated.

Actual behavior:

3) The TextEdit window is tiled on startup. I then have to float and reposition it manually.

I actually have two or three small utility windows open at any one time, so this means every time I want to start `chunkwm` I have to manually refloat and reposition all of these windows, which sort of defeats the purpose of a window manager.

**Comment by koekeishiya** [comment]
fixed on master.

**Comment by arxanas** [comment]
Thanks for fixing this so fast!

It looks as if when I start up `chunkwm`, the windows are repositioned and resized, but then set to float. Is there any configuration I can set to avoid the initial repositioning and resizing?

**Comment by koekeishiya** [comment]
> It looks as if when I start up chunkwm, the windows are repositioned and resized, but then set to float. Is there any configuration I can set to avoid the initial repositioning and resizing?

Uh, I don't believe that this is possible to fix with the current structure.

The reason that this is happening, is because the tiling plugin is loaded, and at that point it will tile the currently visible windows. After this has happened, the rule will be processed, and the window will be marked as floating.

I think this should only be a problem if the window in question is visible on the desktop that is active when chunkwm is launched the first time, but I cannot say so for sure.
