### ISSUE TITLE
Monocle keeps top spacing

### ISSUE THREAD

**Issue by emerinohdz** [koekeishiya/chunkwm#314]
Monocle mode keeps a space at the top, that cannot be removed. I'm using chunkwm with monocle mode by default to keep windows in fullscreen, however even after setting gaps to 0 a space is kept at the top of the window.

<img width="1435" alt="screen shot 2018-01-16 at 1 23 05 am" src="https://user-images.githubusercontent.com/764807/34981281-e417dd82-fa5b-11e7-9a98-cd72f7cf26ef.png">

**Comment by dominiklohmann** [comment]
The setting you're looking to change is `global_desktop_offset_top`:

```
chunkc set global_desktop_offset_top 0
```

_gap_ is the spacing between windows.
_padding_ is the outer spacing.

**Comment by koekeishiya** [comment]
This could also be because (afaik) the macOS Terminal.app is sized to a multiple of the font-size, meaning that it does not resize "smoothly".

I don't use Terminal.app though, so I'm not sure about that.
I'm unable to reproduce this with any applications that I use, so I don't see this as a bug in chunkwm.
