### ISSUE TITLE
Mouse drag w/o modifier

### ISSUE THREAD

**Issue by blahsd** [koekeishiya/chunkwm#320]
With regards to mouse dragging a window over another to swap it, which currently requires to hold a  modifier key (fn by default); would it be possible to have this behaviour configurable to not require any modifier key? So just mouse dragging? 

Thank you! And sorry if it's somehow possible and it's just me who didn't figure it out.

**Comment by matthewdias** [comment]
Wouldn't that not allow you to interact with windows at all?

**Comment by blahsd** [comment]
You're right, my bad. Somehow I thought that even with the modifier key it was only activating the windows-swap if the click was happening on the menu bar – which turns out is not correct. So the feature I was proposing would also need to only work if the click originates on a window's menu bar. Now I'm not sure it's doable without some further development.

**Comment by koekeishiya** [comment]
It's certainly doable, but requires a very different design from what is currently implemented. 
Because there is a rather huge difference, I don't think these two features can co-exist.

With that said, I think the modifier + click-anywhere approach feels more consistent with the other features chunkwm provides (see move floating windows by \<mod> + clicking anywhere in the window) as well as the bsp-layout-resize which also uses a modifier.

**Comment by blahsd** [comment]
I see your point of view. For what is worth, I was hoping to get it to work mouse-only just because that would allow me to move windows around even when I'm slumping over my desktop with no hands on the keyboard, but I definitely see that it would be a very cumbersome thing to implement. Thank you for your time though, and thank you for the great job you're doing with both this and skhd.

**Comment by koekeishiya** [comment]
I'm gonna close this as a won't implement, however, you could definitely look into remapping extra mouse-buttons as mentioned by matthewdias.
