### ISSUE TITLE
Windows no longer spawn left

### ISSUE THREAD

**Issue by jessemillar** [koekeishiya/chunkwm#322]
After updating via Homebrew to `0.3.0` yesterday (on macOS 10.12.6 (16G1114)), new windows no longer spawn on the left side of my screen. They spawn horizontally at the top which makes me think that [my `.chunkwmrc`](https://github.com/jessemillar/dotfiles/blob/cec1fd0fa96b1a1598529b4aca443bf7345ba320/.chunkwmrc#L21) is no longer being honored. Is this a known issue?

**Comment by koekeishiya** [comment]
This is because the `optimal` split mode detects that it should do a horizontal split, instead of a vertical split. I don't recall touching this part of the code at all between this and the previous release.
If you have changed monitor resolution, or desktop padding / gaps, that could be the reason.

In any case, you can try to lower the *optimal_split_ratio* (https://github.com/jessemillar/dotfiles/blob/cec1fd0fa96b1a1598529b4aca443bf7345ba320/.chunkwmrc#L22) and that should make it do a vertical split again. Do try and keep the number as close as possible to the golden ratio for best results.

**Comment by jessemillar** [comment]
Ah. That makes a lot of sense. I did recently change my desktop padding/gaps (right before the update). Does `bsp_spawn_left` just dictate which direction the windows "spiral" in according to `optimal_split_ratio`? I falsely assumed that it would mandate a vertical split with the new window on the left for the first split (the second window to be added to a monitor).

**Comment by koekeishiya** [comment]
It basically represents whether the window should become the left-child leaf or the right-child leaf in a node.

The node is just a container with two leafs (windows) and has a split-mode which can be vertical or horizontal. The left-child in a vertical split is the left-window and the left-child in a horizontal split is the top-window.

**Comment by jessemillar** [comment]
That did. Thank you.
