### ISSUE TITLE
Implement focus follows mouse without autoraise / optional autoraise

### ISSUE THREAD

**Issue by reidlevesque** [koekeishiya/chunkwm#332]
I'd like to specify a delay in ms before ffm raises the window. This would make getting to floating windows easier so that you don't necessarily need to hold down fn (or whatever modifier you have set). Is this possible?

**Comment by koekeishiya** [comment]
I want to give another attempt at implementing focus-follows-mouse *WITHOUT* autoraise before any changes is going to happen here.

I had a semi-working ffm without autoraise in the past, but it had a couple of issues that I didn't know how to solve back then. I have some new ideas for how to deal with this now.

**Comment by reidlevesque** [comment]
That would be even better :)

**Comment by paanvaannd** [comment]
Thank you for your work on this, @koekeishiya! :+)

While I agree that ffm w/o autoraise would be a great addition as well, I would like to voice my support for a setting for ffm delay as well. If I understand this correctly, even if autoraise were delayed or not automatic, then mousing over a window would focus it but not bring it to the front? In that case, the Menu Bar for that application will be the one that is displayed.

A frequent issue I face is that I have an app on the bottom-right of the screen and want to get to the Menu Bar items for that application. So I move the mouse diagonally to the top-left as I normally would but by that time, other applications between the bottom-right application and the Menu Bar have been focused, meaning I have to either trace a path around the border of the computer to get to the Menu Bar without mousing over any windows or Cmd + Tab switch to the desired application to show the proper Menu Bar items. The 2nd option is not bad but it would be great to not have to do this frequently through the implementation of ffm delay.

Is there an existing solution to this issue I face or would that be something that would only be handled by some sort of ffm delay?

**Comment by paanvaannd** [comment]
@matthewdias Ah, I had turned that off, but thank you for pointing me to that handy shortcut combo! Those apps seem neat as well, but I will stick with your proposed keyboard shortcut solution for now.

I would still love to see ffm w/o autoraise or ffm + delay (or both?) implemented eventually!

**Comment by koekeishiya** [comment]
You can currently use `chunkc set ffm_bypass_modifier <..>` to set one (or multiple) modifiers that can be held down to temporarily disable ffm.

**Comment by ferrao** [comment]
Imho ffm with autoraise is impossible to use. 

What I always love and used ffm for in other desktop environments was precisely the fact that I could change focus without altering the window z-positioning. 

Perhaps I am missing some use case here, but until @koekeishiya or somebody finds a way to have ffm w/o autorise I am forced to disable this.

**Comment by mbigras** [comment]
I'm very excited about the `chunkc core::load ffm.so` plugin.

If I use it with focus follows mouse on iTerm2 then I'm able to have focus follows mouse for my text edit or(sublime in a different window) my terminal, and the panes inside my terminal.

The problem I'm having is when moving across the slight gap from iTerm2 to sublime sometimes a window underneath will get triggered and move up in the z axis into focus. This will happen randomly, about once every 20 or so times I move across.

If I understand this is the "autoraise" aspect of the ffm plugin.

From looking at the code it looks like if I increase the `mouse_motion_interval` variable then `ShouldProcessEvent` will be false when I try to jump the gap in from iTerm2 to sublime.

Am I understanding this?

https://github.com/koekeishiya/chunkwm/blob/6078c63a50c6fd3d5101b82223ed6caccfa61e77/src/plugins/ffm/plugin.cpp#L215

https://github.com/koekeishiya/chunkwm/blob/6078c63a50c6fd3d5101b82223ed6caccfa61e77/src/plugins/ffm/plugin.cpp#L100-L107

Example of chrome jumping into focus when I try to jump the gap

<img width="307" alt="Screen Shot 2019-03-20 at 6 14 28 AM" src="https://user-images.githubusercontent.com/5590632/54689475-d8ad3000-4adc-11e9-87c2-06a751befff1.png">
<img width="231" alt="Screen Shot 2019-03-20 at 6 14 43 AM" src="https://user-images.githubusercontent.com/5590632/54689490-dd71e400-4adc-11e9-8d13-cd9280fa1a99.png">

**Comment by lesgrieve** [comment]
Åsmund, you would be legendary if you provided some solution to FFM without raise.  Anything, make it off by default and mark it as in development.  I don't care about the menu.  I use the menu 4 times a day, I copy text from one window to another 10 times an hour.  To access the menu, I can tile to top and don't mind clicking the window.

**Comment by koekeishiya** [comment]
The previous solution I had for ffm without autoraise was fairly primitive, but mostly worked. It revolved around intercepting keyevents and rerouting them to the process which had last been seen below the cursor. it was sometimes a bit janky to have the correct window of said application receive the input, and not the former main window - but I had a workaround that seemed to work fine.

The main issue with this method was that we would also prevent ALL hotkeys from registering. IIRC cmd+tab, cmd+` and other mission control shortcuts would no longer trigger properly, because we rerouted them from mission control and to our new target. There is a "target process for this event" in the eventrecord we process, but that never specifically targets mission control, so we can not filter these that way. You could of cource add an event whitelist that says never forward events that look like this, and you could allow system shortcuts to work properly.

Again, this method only reroutes key-events (mostly what we care about), but the application does not gain focused state, and so the menubar will remain inactive - the window wil be drawn as if it was inactive, etc. The solution I had used the `CGEventTap` API to intercept keyevents and `CGEventPostToPSN` to reroute them, in case anyone else is interested in trying this.

As a sidenote there is functionality supported in macOS for activating an application (note: application only) WITHOUT actually having the application be raised. You can test this if you have application A focused, and while you click to focus application B, hold ctrl + alt. 

What happens when you do this, is that somewhere in the pipeline (most likely in AppKit). There is a lot of stuff happening through multiple systems, but eventually inside the SkyLight framework a function called SetFrontProcessInternal is called. This function basically checks to see if the application is already active - give the new window focus. If the application was not already active, it posts an event of type kCGSEventResume (0x14). Function signature: `PostCGSEventToProcess(CPSProcessRec *, CGSEventType, ushort, ushort, uint, int, CPSProcessSerNum);`

The only difference between a regular process activation that also raises the application to the front, and the process activation that occur when holding ctrl + alt and focusing the application, is a field called "userGenerated". By default this is 0, but is reported as 1 when ctrl + alt is held.

The real solution for ffm without autoraise on macOS would imo have to leverage this part of the pipeline. Maybe someone more knowledgable than me would be able to take this a step further and actually implement a POC.

**Comment by koekeishiya** [comment]
I have managed to create a working proof of concept of focus follows mosue without autoraise, however so far it only works when moving between different applications, and not different windows of the same application.

**Comment by koekeishiya** [comment]
@lesgrieve Updated with a proof of concept on the master branch. As mentioned earlier it only works between different applications, and not between multiple windows of the same application. I'm still in the process of reverse engineering this, so consider it experimental.

To enable autofocus behaviour instead of autoraise, add the following to *.chunkwmrc* before the command that loads the *ffm* plugin: `chunkc set ffm_disable_autoraise 1`

**Comment by koekeishiya** [comment]
Real autofocus has been implemented on master.

**Comment by dominiklohmann** [comment]
> Should be working fine, but I have not yet done extensive testing, so for all intents and purposes consider it experimental.

After having played around with it for an hour, I can say this much:

- This is definitely amazing, and
- chunkwm needs some way to remove focus from the moved-from window if focus moves to a window of the same application—the traffic lights get a little confused here.

**Comment by koekeishiya** [comment]
> chunkwm needs some way to remove focus from the moved-from window if focus moves to a window of the same application—the traffic lights get a little confused here.

Should be fixed.

**Comment by reidlevesque** [comment]
@koekeishiya @dominiklohmann How did you manage to configure chunkwm to disable autoraise? I was playing around with HEAD and when my mouse moved to a new window, it still got raised. I am running macOS Mojave 10.14.4. Here is my config in case you see something I missed:

```
#!/bin/bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

chunkc core::hotload 0

chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1
chunkc set ffm_disable_autoraise         1

chunkc core::load ffm.so
```

**Comment by jonathanwilner** [comment]
Same issue for me - with latest HEAD each time since the experimental commit.

**Comment by koekeishiya** [comment]
@reidlevesque @jonathanwilner 
That config looks right. I have not tested this with SIP enabled, incase any of you have that - so might be worth a try, although I don't remember seeing anything that would make me think that was required. Make sure that the ffm plugin on  your system was actually updated and that the correct version is running. Otherwise I'm not sure. This was reversed through statically reading through the disassembled code for the WindowServer, as well as observations I made on my system with regards to how the WindowServer responded to various events and actions.

All I know is that it works perfectly on my 10.14.4 system, and it appears to also have worked for @dominiklohmann. I can't think of any particular settings that I may have changed that would affect this.

**Comment by dominiklohmann** [comment]
> All I know is that it works perfectly on my 10.14.4 system, and it appears to also have worked for @dominiklohmann. I can't think of any particular settings that I may have changed that would affect this.

Can confirm the new ffm works for me with these settings on 10.4.4. Don't really think standby on float makes any sense without autoraise.

```
chunkc set window_float_topmost  0
chunkc set ffm_bypass_modifier fn
chunkc set ffm_standby_on_float 0
chunkc set ffm_disable_autoraise 1

chunkc core::load ffm.so
```

**Comment by reidlevesque** [comment]
I did some more investigation and it looks like it works between certain applications but others raise their windows. 

In my limited testing I've found that these applications get focus but don't raise (i.e. behave as expected):
* iTerm2
* App Store
* Spotify
* Safari
* Calendar
* Messages
* Reminders
* Microsoft Word
* Microsoft PowerPoint
* Microsoft Excel
* Postman

These applications get focus but **DO** raise (i.e. **DON'T** behave as expected):
* Firefox
* Slack
* Visual Studio Code
* IntelliJ IDEA

Looking at the logs there is nothing obvious that differentiates those apps.

I'm not sure why only those applications raise.

**Comment by dominiklohmann** [comment]
I reproduced this with VS Code and Slack. In the case of VS Code I expected this to be a general issue with Electron, but it is in fact not—other Electron applications (e.g. Discord) behave as expected here.

**Comment by koekeishiya** [comment]
I really dislike macOS sometimes.. I could probably find a way around this, but that would rely on chunkwm-sa. I have to say I don't feel like investing more time into this for the time being.

**Comment by mbigras** [comment]
I think Slack recently updated to `Version 3.4.2 (Direct Download)` now focus follows mouse without autoraise is working for me everywhere. These are the relevant lines in my `~/.chunkwmrc` file:

```
#!/bin/bash
# ...
chunkc set ffm_bypass_modifier fn
chunkc set ffm_standby_on_float 0
chunkc set ffm_disable_autoraise 1

chunkc core::load ffm.so
```
