### ISSUE TITLE
fn+click border not overlayed on focus border

### ISSUE THREAD

**Issue by hyperum** [koekeishiya/chunkwm#395]
The red fn+click border for moving window positions in bsp is not drawn in the same place as the border on the focused window - sometimes, it can be misaligned on the top and bottom; I have also seen it misaligned on the sides. This means some of the focus border shows beside the red border.

**Comment by koekeishiya** [comment]
Resolved at master. The following is a wall of text describing why this issue is a thing in the first place.



Initially I thought this was because we used integers instead of floating points for the border-calculations, but turned out the problem is that the window dimensions actually slightly differ from the region dimensions due to macOS not supporting floating point values for the window position / size, so it does rounding, and our preselection-borders rounded differently.

I have changed how we calculate the preselection dimensions to handle this situation. It is not perfect, but it is a lot better now than it was, and probably as good as we can get it.

The reason this difference between the borders can occur, is that the focused border is drawn using the actual windows dimension, where as the preselection borders are drawn using the dimensions of the node that the window belongs to.
