### ISSUE TITLE
Stopped working with iTerm after edit in skhdrc

### ISSUE THREAD

**Issue by FinnFrotscher** [koekeishiya/chunkwm#396]
chunkwm stopped moving focus when focused on iterm.
it supposed to change focus on `alt-hjkl`, and it works for every other app (chrome, firefox, atom, slack, etc) just not when focus is on iterm. 
It happened after i added some more tiling commands to the `skhdrc` file, like:`ctrl + alt - n  : chunkc tiling::monitor -f`

## My dotfiles:
https://github.com/FinnFrotscher/dotfiles

**Comment by koekeishiya** [comment]
This is because terminal applications offer a setting called "Secure Keyboard Entry".
You can disable this in the menubar (focus iTerm2, click the iTerm2 name in the menubar and disable Secure Keyboard Entry).

The following picture shows this in Terminal.app, but it should be located at the same place for iTerm2:
<img width="337" alt="screen shot 2018-05-03 at 20 29 35" src="https://user-images.githubusercontent.com/6175959/39595860-f1c26c68-4f10-11e8-8069-e649edcf120e.png">

**Comment by FinnFrotscher** [comment]
thank you so much. that was it 💯 👍 🎉
