### ISSUE TITLE
Is there any way to port this over to Windows 10?

### ISSUE THREAD

**Issue by lesseradmin** [koekeishiya/chunkwm#399]
I honestly love this window manager, I've used i3 and bspwm before on arch, but I still think that chunkwm is more convenient and has a lot of awesome features. I was wondering if there was any way to port this over to Windows 10. Would it be possible to keep a lot of the underlying logic the same and just have new API calls to actually move the windows switch between them?

If this is at all possible maybe create a wrapper class for all of the API calls and make the appropriate calls based on which OS the platform is running on.

Once again thanks for all of the awesome work @koekeishiya.

**Comment by koekeishiya** [comment]
I know there are functions to locate, move / resize etc. windows in the Windows API, but I have no idea if it is possible to listen for, or otherwise get notified about window creation, application launches and similar, which is where it all starts (from chunkwm's pov).

I also don't think Windows is posix compliant, so that would require quite a bit of work as well.
