### ISSUE TITLE
Screenshots (both area selection and entire window) won't work

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [koekeishiya/chunkwm#410]
I don't think I've seen this issue anywhere, but whenever I hit cmd + shift + 4, the crosshairs don't show up, and fullscreen screenshots won't work either (even with the workaround I saw in the wiki).

**Comment by nanzhong** [comment]
I'm unable to reproduce this. I've tried on both a desktop that has a fullscreen (native macOS fullscreen) window and on a desktop with multiple windows.

Could you provide more details to reproduce? What versions are you running?

**Comment by yamini-krishnamurthy** [comment]
chunkwm - 0.3.6
skhd - 0.0.14
My laptop is a 2017 MacBook Pro
I used this video to set everything up - https://www.youtube.com/watch?v=ZUMucXKU4Fw
Pretty sure I made only one change to chunkwmrc, just to make the windows centered without the menu bar.

**Comment by koekeishiya** [comment]
If you just copied the default sample configs, there is probably a bind in *.skhdrc* that does something when cmd + shift - 4 is pressed, which is why it does not work for you.

I suppose these kinds of binds should not be part of the config that is shipped as an example, but it is pretty much just a copy of my personal config, and I kind of expect people to customize it, and NOT use it as is.

**Comment by yamini-krishnamurthy** [comment]
Yup, you were right. Derp
