### ISSUE TITLE
unable to close iterm with no titlebar 

### ISSUE THREAD

**Issue by yuhuanq** [koekeishiya/chunkwm#435]
When no titlebar is enabled for iterm, chunkwm fails to close the windows. Any ideas? 

## reproducing

preferences -> profiles -> windows -> style -> select `no titlebar` 

`chunkc tiling::window --close` no longer works

**Comment by dominiklohmann** [comment]
All `chunkc tiling::window --close` does is tell the system that the close button on the selected window was pressed. Since there's no such button if you run iTerm2 with the no titlebar option, you will have to work around this. 

If you have a bind that triggers this action for you, you can simply change it to press `cmd - w` instead if iTerm2 is the active window. This should do the trick for almost all use cases.

**Comment by yuhuanq** [comment]
I see, thanks for the quick reply!
