### ISSUE TITLE
[plugin|tiling] Focus monitor fails on empty monitors

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#464]
FocusMonitor is currently not able to give focus to monitors that do not have any open windows.
This is because we rely on being able to give an existing window focus, to activate said monitor.
This is because macOS only has a concept of a key-window, and the active monitor is simply the monitor that holds the key-window.

We are unable to actually give focus to the macOS finder desktop window (that you focus when you click on your wallpaper, basically). 

We can support this by doing a sophisticated check to see whether the monitor has open windows or not. If the monitor is empty, we synthesize a left-mouse-down event in the center of the monitor.
If the monitor has open windows, but chunkwm are unable to interact with said windows, we do NOT synthesize a left-mouse-down event, to prevent accidentally clicking some ui-element.

**Comment by dominiklohmann** [comment]
So with this the monitor wraparound does not work on an empty space when trying to go to the next or previous window. I believe this is the case because currently, asking chunkwm to focus the next or previous window with no window focused on the active space will instead try to focus the first or last node in the tree respectively, which obviously fails.

**Comment by koekeishiya** [comment]
fixed on master.

**Comment by xiamaz** [comment]
This still seems to break when using `chunkc tiling::monitor -f <prev/next>` to switch monitors, which will cause the focus to jump back if the selected monitor is empty.

Directly focusing with monitor id seems to work correctly.
