### ISSUE TITLE
iTerm window height inconsistency 

### ISSUE THREAD

**Issue by the-c0d3r** [koekeishiya/chunkwm#468]
I'm not sure if this should be an issue in chunkwm repository or the iTerm's but here it is. Whenever I spawn more than 1 iTerm window on the desktop, the height of the window is different. I know there's option in iTerm "Adjust window size when changing font size" but it is disabled. And both windows are using the same font size, same font, same profile. But their window height is different. 
I also looked up online, and read a lot of people saying terminal's column height depends on the font size and number of lines. 
But this issue is bugging me every time I use iTerm, (which is almost all the time, since I work in vim, and ssh a lot) and spawn many windows.

First picture is when using just 2 window, left and right.
![screen shot 2018-07-25 at 9 38 02 pm](https://user-images.githubusercontent.com/4526565/43204295-12b55420-9053-11e8-9dd8-e36597bca27a.png)

Second picture is when using more than 2. That is 1 big on the right, and 2 horizontal split on the left. 
![screen shot 2018-07-25 at 9 37 35 pm](https://user-images.githubusercontent.com/4526565/43204355-33766258-9053-11e8-8b6e-64ef2ab32445.png)

So I just want to know if anyone experience this same problem as I did. And if there is any workaround I can do to fix that. Lastly, thanks for writing this great piece of software. The dock alpha fading effect is so cool. 👍

**Comment by crisidev** [comment]
I have the same issue, but I think it is related to also font size and iterm configs and not too much to chunkwm..

**Comment by koekeishiya** [comment]
This is indeed related to terminal implementation details. I dont have this issue in Kitty, as the author has approached the problem differently IIRC

**Comment by dominiklohmann** [comment]
You can change this behaviour in the advanced iTerm2 settings. Currently without a laptop (keyboard replacement...), so I cannot look up the exact wording, but it basically changes the padding to not make the window size depend on the line height.

**Comment by crisidev** [comment]
I think I found it. Try to set in advanced iTerm2 settings

```
Use a more theoretically correct technique to measure line height
```

to True.

Thanks @dominiklohmann

**Comment by the-c0d3r** [comment]
Thanks for the quick responses. I tried the setting that @crisidev found. The issue still exist. Then I thought it's also related to the margin/padding I set for iTerm. Disabled the margin, set the advanced setting to true and restarted iTerm. But it still happens, but this time, the same window split, left side is higher.

I think if I use other terminals, they may not have this issue, but iTerm has a lot of good features that I use daily. So I can't switch just yet. 

I did another test, I used iTerm without the title bar. I switched back to normal one with the title bar. The height difference seems lower than previous.

**Comment by koekeishiya** [comment]
IMO the better solution to handle this very issue (from a terminal perspective) is to not mess around with the window size, but rather pad the render-region itself. That way, the windows will remain aligned as per the window managers requests.

I suppose you could open a request in iTerms repository. It is my understanding that iTerm now already supports inner-padding? Thus, I assume that system could be built upon to support this.

I believe this is what the Kitty author has done, but I can not say for sure.

**Comment by koekeishiya** [comment]
So what the optimal split mode is doing, is that it uses a ratio between the tilable regions width and height, to determine whether it should do a vertical or horizontal split. So if these values change depending on display resolution, configured padding (visible dock / menubar) and so on, that could impact this.

What you could do here is to tweak the *bsp_optimal_ratio* value, to be a bit lower, if you want a vertical split. The default value is the golden ratio, and I would recommend using a value as close to this as possible, that works for your configuration.

**Comment by crisidev** [comment]
@the-c0d3r have you restarted fully iTerm after changing the config? It looks to be working for me..

**Comment by net** [comment]
@koekeishiya To be clear, the issue here is not that iTerm snaps to the cell grid. iTerm provides an option to enable continuous sizing (_Terminal windows resize smoothly_), which will inner-pad the window if necessary. Even with the setting enabled, there is still at times slight vertical misalignment between two side-by-side iTerm windows positioned by chunkwm.

kitty also has the same issue. Here is a screenshot of the intersection of three kitty windows positioned by chunkwm:

<img width="120" alt="screen shot 2018-07-26 at 5 44 04 pm" src="https://user-images.githubusercontent.com/6983821/43290373-e9908aa2-90fb-11e8-925f-6673a9977fb4.png">

This issue, for me, only manifests at certain y-coordinates.

@crisidev I tried that setting—and restarted iTerm—with no success. It did mess up iTerm's letter spacing, so I disabled it.

**Comment by net** [comment]
Actually, I can't comment on whether this is @the-c0d3r's issue or not. It is _an_ issue, which if not the same is similar and perhaps "the real issue". @the-c0d3r, if you don't already have it enabled, enable _Terminal windows resize smoothly_ in iTerm's advanced preferences.

**Comment by koekeishiya** [comment]
@net Are you also able to reproduce this with non-terminal applications? If that is the case, then that could very well be a rounding error or whatever in chunkwm's logic.

I have not had this issue with Kitty ever since I started using it, on diff display resolutions and whatever. Maybe I just haven't triggered the small edge case where it actually is possible for that to happen.

**Comment by dominiklohmann** [comment]
Got my laptop back, this is the setting for iTerm to automatically add padding to allow any window size:
