### ISSUE TITLE
Plugin folder is moved but the path in .chunkwmrc remains the same

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/chunkwm#493]
Updating using brew - chunkwm stopped working. I looked into the output and here is a print
```
2018-08-16 18:38:58 ERROR: chunkwm: '/Users/noname/.chunkwm_plugins/border.so' (border.so) is not a valid chunkwm plugin!
objc[1408]: Class OverlayView is implemented in both /Users/noname/.chunkwm_plugins/border.so (0x1036028a0) and /Users/noname/.chunkwm_plugins/tiling.so (0x103629530). One of the two will be used. Which one is undefined.
2018-08-16 18:38:58 ERROR: chunkwm: '/Users/noname/.chunkwm_plugins/tiling.so' (tiling.so) is not a valid chunkwm plugin!
2018-08-16 18:38:58 WARN : chunkwm: plugin '/Users/noname/.chunkwm_plugins/ffm.so' not found..
```
I haven't installed the ffm.so plugin so don't worry about that one. The one troubling me is that is states that tiling.so, isn't a valid plugin. Im not sure what changed, i used 0.3.6, and i have now updated to 0.4.6.

Updating using brew, states in the install message, that the plugin folder have been moved.
```
NOTE: plugins folder has been moved to /usr/local/opt/chunkwm/share/chunkwm/plugins
```
This however is not reflected in the .chunkwmrc file which states that the plugin folder is ``` ~/.chunkwm_plugins```

Should i move the plugins from ```/usr/local/opt/chunkwm/share/chunkwm/plugins``` to the folder ``` ~/.chunkwm_plugins``` or should i replace the path in .chunkwmrc?

I guess replacing the path in ```.chunkwmrc``` makes it easier to update - but it is unclear what the intended purpose of the move is?

[SOLVED]
This was solved replacing the path in ```.chunkwmrc```. However it's not clear if the plugins should be moved into ``` ~/.chunkwm_plugins``` or if ```.chunkwmrc``` should be edited, also in examples?

**Comment by dominiklohmann** [comment]
The plugin folder has only moved for the Homebrew installation and the example configuration shipped with Homebrew also has this changed path. So yes, change to the (not so) new path. 

The change has been made to be more in line with Homebrew guidelines back when we tried to get chunkwm into the Homebrew/core formulae repository. This attempt failed because of the code signing necessity, but the directory was never changed back for Homebrew installations.

<hr />

> Should i move the plugins from /usr/local/opt/chunkwm/share/chunkwm/plugins to the folder ~/.chunkwm_plugins or should i replace the path in .chunkwmrc?

Either option works, but the latter requires you to manually move your plugins after every update, because Homebrew will install them in the new directory.

**Comment by brorbw** [comment]
Alright - I consider this closed then.
