### ISSUE TITLE
Recurring "Accessibility Access" requests under macOS Mojave

### ISSUE THREAD

**Issue by mgiugliano** [koekeishiya/chunkwm#517]
I am under macOS Mojave 10.14 and chunkwm (v. 0.4.6) has restated prompting "Accessibility Access", despite being already granted access. 

Deselecting and selecting chunkwm from the list of apps from Security & Privacy in System Preferences had no effect.

**Comment by dominiklohmann** [comment]
This and koekeishiya/skhd#52 (both opened by you) have the same underlying cause. Your binaries are not signed with a code signing certificate. Instead of disabling and then enabling the accessibility access, you have to remove the list entries, restart chunkwm/skhd, enable the new entries and then restart chunkwm/skhd.

If you use a self signed code signing certificate to sign chunkwm/skhd after updating you won't have to bother with this after every chunkwm/skhd update.

**Comment by crisidev** [comment]
You can find guide on how to create and use the certificate in the Chunkwm tap repo README.

**Comment by dominiklohmann** [comment]
@crisidev @koekeishiya Maybe we should consider handling this just like `llvm --with-lldb`. chunkwm and skhd are not going to be moved to Homebrew-core in the foreseeable future anyways, so maybe just add it there and require certificates named chunkwm_codesign / skhd_codesign respectively.

**Comment by koekeishiya** [comment]
@dominiklohmann @crisidev 

I wish I could just add the process to the accessibility list through an API, granted the app was run with root permissions, and we could just have had a cmdline argument..

I'm all for whatever solution makes this situation less error-prone for the user.

**Comment by dominiklohmann** [comment]
> I'm all for whatever solution makes this situation less error-prone for the user.

Do signed releases through Homebrew Cask – that's the easiest way. If, however, signed binary distribution is not what you want to do (understandably so):
- Self-signing will always require the user to create a self-signed code signing certificate (e.g. see [instructions for lldb](https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt)). Homebrew Core denied us entry for that reason (although giving lldb a special pass), which is why @crisidev maintains the custom tap repository. 
-  Require a certificate to exist with a certain name before installing, which can then be used to sign from within the formula. If the certificate does not exist, link the user to a step-by-step guide for creating one.

**Comment by mgiugliano** [comment]
@dominiklohmann I followed exactly your instructions, with no success.

**Comment by jdkschang** [comment]
While I went through the 'lldb' instructions and setup a **chunkwm-cert**, restarted, etc., the services still failed and continued to bring up the accessibility prompt. For me the only fix was to completely _uninstall_ chunkwm and skhd and _reinstall_ followed by a **restart**.

**Comment by dominiklohmann** [comment]
@jdkschang Did you stop the service prior to signing the binary?

This is my order that I have not changed for over a year now (similarly for skhd), where `chwm_codesign` is the name of my codesigning certificate.

```sh
# Stop the service first, then update
# This makes sure that chunkwm does not get run immediately after updating
brew services stop chunkwm
brew reinstall koekeishiya/formulae/chunkwm --HEAD

# Now codesign the binary
codesign -f -s "chwm_codesign" $(which chunkwm)

# Restart the service
brew services start chunkwm

# This last part is optional and requires SIP to be disabled 
# Do this only if you need the chwm-sa extension
sudo chunkwm --uninstall-sa
sudo chunkwm --install-sa
pkill Dock
```

**Comment by jdkschang** [comment]
@dominiklohmann yes I did stop the service prior to signing the binary; essentially followed your snippet (not including the fantastic [[instruction for lldb][https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt]]

**Comment by koekeishiya** [comment]
I think all the information necessary regarding this has already been posted in this issue.
I don't want to have to provide codesigned binaries, so closing this as I consider it resolved.
