### ISSUE TITLE
bsp_spawn_above option? Allow vertical tiles to default to below when using optimal

### ISSUE THREAD

**Issue by BlueDrink9** [koekeishiya/chunkwm#556]
Is there a way to make new windows open below the current one, rather than above it when the current container's height is larger than its width, using bsp_split_mode optimal?

Similar to bsp_spawn_left, except for vertical tiling rather than horizontal.

**Comment by dominiklohmann** [comment]
If you use the optimal split mode, the `bsp_optimal_ratio` (default: golden ratio) determines the threshold for the width/height ratio for switching between vertical and horizontal splitting. 

`bsp_spawn_left` mode simply means that new nodes will be inserted as left child nodes (instead of right), which with a non-rotated tree means that horizontal splits go left and vertical splits go top.

**Comment by BlueDrink9** [comment]
Oooh, `bsp_spawn_left` applies to vertical ones as well? Thank you for clarifying!
