### ISSUE TITLE
Chunkwm stopped working after High Sierra update

### ISSUE THREAD

**Issue by teichholz** [koekeishiya/chunkwm#581]
Already double checked everything and followed #295 with no success. Weirdly enough an item for chunkwm in the accessibility tab only shows up when starting it as a service with homebrew and not when executing it in the directly. chunkwm just keeps telling me that it has no access to the accessibility features. 

Is there anything I can do?

**Comment by dominiklohmann** [comment]
> Is there anything I can do?

Basic troubleshooting order for accessibility (AX) prompts is always like this:
- Stop the brew service `brew services stop chunkwm`
- Remove the entry for chunkwm in the AX settings panel
- (optional) update and codesign chunkwm (see https://github.com/koekeishiya/chunkwm/issues/517#issuecomment-460433819)
- Restart the service `brew services start chunkwm`
- Allow newly added chunkwm entry in the AX settings panel
- If issues still exists, logout and back in again

The codesigning step is really recommended, because you won't have to deal with AX permissions afterwards.

> High Sierra

Highly unlikely, but — the issue might also be related to High Sierra, since the testing usually happens on the latest stable release, which currently is Mojave 10.14.3.

**Comment by koekeishiya** [comment]
Probably the same issue as in https://github.com/koekeishiya/chunkwm/issues/582
We do check for this in the code though, so I'm not sure why you wouldn't get that error message.
