### ISSUE TITLE
CGSSpace related functions

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#72]
Needs more investigation, but I may have a way to be able to use these without having to kill the dock and all that annoying crap.

**Comment by choco** [comment]
Last time I checked the Dock binary, I looked if it was listening for some notifications, but I found nothing. I'd love to be proven wrong though :)

If we want interact with spaces and keep the Dock happy it would probably be easier through the scripting addition, it shouldn't be too hard to find the method used for example to create a new space and just call it from there. More complex operation would probably be harder.
The only issue is that, since Sierra I think, they started to rewrite the Dock app in Swift, so with the new macOS release (probably 5 days from now for the first beta :O) they may break any development we make on this from.

**Comment by koekeishiya** [comment]
Going to close this as I randomly lost interest in the topic.
