### ISSUE TITLE
[plugin|tiling] region_locked not respected for non-active space resized windows

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#86]
Already discussed as a possible shortcoming in the original implementation, didn't think much of it but it happens to me many times when opening a link in another space.
The same mechanism is probably really useful for resolution change so it'll probably a good enhancement to develop down the road.

**Comment by koekeishiya** [comment]
I haven't really looked at this since forever. Is this referring to this function: https://github.com/koekeishiya/chunkwm/blob/60f15ef948c9f7003ac9c013a57934065ad23631/src/plugins/tiling/node.cpp#L229

call site: https://github.com/koekeishiya/chunkwm/blob/d4920c3a3317e5d7ab5887b7a300ba5a9d753aed/src/plugins/tiling/plugin.mm#L1399

Note to self:
This problem can be solved by finding the space that the window that was moved / resized belongs to. If this space is the active space for its monitor, we do the refresh as it is done currently and if not we flag the space (or the window itself?) to refresh upon next activation.

**Comment by koekeishiya** [comment]
Fixed at master.
