### ISSUE TITLE
[plugin|tiling] iTerm2 with "No Title Bar" setting enabled won't tile

### ISSUE THREAD

**Issue by joshuap** [koekeishiya/chunkwm#92]
When I go to Profiles -> Default -> Window -> Style, select "No Title Bar", and relaunch iTerm2, `chunkwm` will not resize the terminal windows. I feel like this was also an issue with kwm, but I couldn't find discussion about it here. The advanced "Hide iTerm2 from the dock" setting does seem to work (at least sometimes) in `chunkwm`, interestingly.

**Comment by oxyc** [comment]
Works for me with iTerm2 3.1.beta.3

**Comment by joshuap** [comment]
@oxyc you're right, it's working for me after upgrading to the 3.1 beta:

```sh
brew cask uninstall iterm2
brew tap caskroom/versions
brew cask install iterm2-beta
```

Thanks!

**Comment by OJFord** [comment]
Same issue with alacritty@master. As this was resolved by upgrading iTerm, I suppose the issue needs to be raised against alacritty? Does anyone know what causes it to break; how iTerm fixed it?

**Comment by koekeishiya** [comment]
The window roles reported by the accessibility API is what causes this.
You can use the window rules system to work around this: https://github.com/koekeishiya/chunkwm/blob/3d6a018222efd1d3b32538380fb6f2c252e3058f/src/plugins/tiling/README.md#window-rules

Typically, something like: `chunkc tiling::rule --owner alacritty --state tile`
If that causes issue with menus, tooltips? and whatever, you need  to get more specific.

You can run the following commands to figure out more about the window.
First, make sure an alacritty window is open in the active desktop. Then write the following commands:
```
chunkc tiling::query --desktop windows

# identify the alacritty window, and it should also contain the string: (invalid)
# run the following command replacing <id> with the window id reported by the previous command
chunkc tiling::query --window <id>
```

Other than this, yes, the developer of alacritty has to make sure the application conforms to the acccessibility standards.

**Comment by OJFord** [comment]
@koekeishiya Many thanks for your reply.

Without title bar:
```
id: 62770
level: 0
name: ...
owner: Alacritty
role: AXWindow
subrole: AXUnknown
movable: 1
resizable: 0
```

With title bar:
```
id: 62707
level: 0
name: ...
owner: Alacritty
role: AXWindow
subrole: AXStandardWindow
movable: 1
resizable: 1
```

Are 'resizeable' and 'subrole' properties that applications set, or does chunkwm derive them based on something else?

**Comment by koekeishiya** [comment]
These properties are queried from the macOS accessibility API.

Regarding the subrole, I'm not completely sure how that is set by the applications, but this can be worked around using the rules-system implemented in chunkwm, and is not a big deal.

The real problem here is that the window is not marked resizable. The reason for this is that the windowing toolkit that Alacritty uses does not set the *NSWindowResizableMask* to the NSWindow's styleMask.

Most frameworks that I've seen have this behaviour (god knows why..) when the window titlebar is disabled. GLFW used by the *Kitty* terminal had the same issue, however the *Kitty* developer made the *hide_titlebar* option re-add the missing *NSWindowResizableMask* manually. as the GLFW API exposes the underlaying NSWindow if desired.

The author of Alacritty could probably fix this the same way.
